#!/bin/sh

DAEMON="/usr/bin/pixelweb"
CONFIG_DIR="/userdata/system/pixelcade"
DAEMON_ARGS="-demo -p $CONFIG_DIR"

start() {
        echo -n "Starting PixelWEB: "
        
        # Start the PIXELWEB daemon
        start-stop-daemon --start --quiet --exec $DAEMON --background -- $DAEMON_ARGS
        RETVAL=$?

	echo "done"
        return $RETVAL
}

stop() {
        echo -n "Stopping PixelWEB: "

        # Stop the PIXELWEB daemon
        start-stop-daemon --stop --quiet --exec $DAEMON
	RETVAL=$?
	
        echo "done"
        return $RETVAL
}


case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        *)
                echo "Usage: $0 {start|stop}"
                exit 1
esac

exit $?
